trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
jobs:
- job: linux
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      'C++ linting':
        YCM_PYTHON_VERSION: '3.9.0'
  steps:
  - script: ./azure/lint.sh
    displayName: Lint
