jobs:
- job: windows_msvc17
  displayName: 'Windows Visual Studio 2019'
  pool:
    # List of available software on this image:
    # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md
    vmImage: 'windows-2019'
  strategy:
    matrix:
      'Python 3.8 64-bit':
        YCM_PYTHON_INSTALLER_URL: 'https://www.python.org/ftp/python/3.8.1/python-3.8.1-amd64.exe'
    maxParallel: 4
  variables:
    MSVC: 16
    MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin'
    COVERAGE: true
  steps:
  - checkout: self
    submodules: recursive
  - script: azure\windows\install_dependencies.bat
    displayName: Install dependencies
  - script: azure\windows\run_tests.bat
    displayName: Run tests
    condition: and(succeeded(), ne(variables['YCM_BENCHMARK'], 'true'))
  - script: azure\windows\benchmark.bat
    displayName: Benchmark
    condition: and(succeeded(), eq(variables['YCM_BENCHMARK'], 'true'))
  - script: azure\windows\send_coverage.bat
    displayName: Send coverage
    condition: and(succeeded(), eq(variables['COVERAGE'], 'true'))
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      CODECOV_JOB_NAME: '$(Agent.JobName)'
