trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
jobs:
- job: windows_msvc17
  displayName: 'Windows Visual Studio 2019'
  pool:
    # List of available software on this image:
    # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md
    vmImage: 'windows-2019'
  strategy:
    matrix:
      'C++ benchmark':
        YCM_PYTHON_INSTALLER_URL: 'https://www.python.org/ftp/python/3.8.1/python-3.8.1-amd64.exe'
        YCM_BENCHMARK: true
        COVERAGE: false
    maxParallel: 3
  variables:
    MSVC: 16
    MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin'
    COVERAGE: true
  steps:
  - checkout: self
    submodules: recursive
  - script: azure\windows\install_dependencies.bat
    displayName: Install dependencies
