jobs:
- job: windows_msvc14
  displayName: 'Windows Visual Studio 2015'
  pool:
    # List of available software on this image:
    # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2015-Server2012R2-Readme.md
    vmImage: 'vs2015-win2012r2'
  strategy:
    matrix:
      'Python 3.7 64-bit':
        YCM_PYTHON_INSTALLER_URL: 'https://www.python.org/ftp/python/3.7.3/python-3.7.3-amd64.exe'
  variables:
    MSVC: 14
    MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\14.0\Bin'
  steps:
  - checkout: self
    submodules: recursive
  - script: azure\windows\install_dependencies.bat
    displayName: Install dependencies
  - script: azure\windows\run_tests.bat
    displayName: Run tests
  - script: azure\windows\send_coverage.bat
    displayName: Send coverage
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      CODECOV_JOB_NAME: '$(Agent.JobName)'
