jobs:
- job: linux
  displayName: 'Linux'
  pool:
    # List of available software on this image:
    # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      # Tests are failing on Python 2.7.0 with the exception
      # "TypeError: argument can't be <type 'unicode'>"
      'Python 3.5 using Clang compiler':
        YCM_PYTHON_VERSION: '3.5.1'
        YCM_CORES: '1'
        YCM_COMPILER: 'clang'
    maxParallel: 6
  variables:
    COVERAGE: true
  steps:
  - checkout: self
    submodules: recursive
  - script: ./azure/linux/install_dependencies.sh
    displayName: Install dependencies
  - script: ./azure/run_tests.sh
    displayName: Run tests
    condition: and(succeeded(), and(ne(variables['YCM_BENCHMARK'], 'true'), ne(variables['YCM_CLANG_TIDY'], 'true')))
